/*
 * UserDeletePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.user.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.common.UserTypeEnum;
import cn.hncu.bookStore.user.business.ebi.UserEbi;
import cn.hncu.bookStore.user.business.factory.UserEboFactory;
import cn.hncu.bookStore.user.vo.UserModel;

/**
 *
 * @author  __USER__
 */
public class UserDeletePanel extends javax.swing.JPanel {
	private JFrame mainFrame = null;
	private String uuid;

	/** Creates new form UserDeletePanel */
	public UserDeletePanel(JFrame mainFrame, String uuid) {
		this.mainFrame = mainFrame;
		this.uuid = uuid;
		initComponents();
		myInitComData();
	}

	private void myInitComData() {
		UserEbi ebi = UserEboFactory.getUserEbi();
		UserModel user = ebi.getSingle(uuid);

		tfdUuid.setText(user.getUuid());
		tfdName.setText(user.getName());
		ptfPwd.setText(user.getPwd());
		strType.setText(UserTypeEnum.getNameByType(user.getType()));

		tfdUuid.setEditable(false);
		tfdName.setEditable(false);
		ptfPwd.setEditable(false);
		strType.setEditable(false);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		tfdUuid = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		tfdName = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		strType = new javax.swing.JTextField();
		btnDelete = new javax.swing.JButton();
		btnBack = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		ptfPwd = new javax.swing.JTextField();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel1.setForeground(new java.awt.Color(0, 51, 255));
		jLabel1.setText("\u7528\u6237\u5220\u9664\u754c\u9762");
		add(jLabel1);
		jLabel1.setBounds(250, 30, 230, 60);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel2.setForeground(new java.awt.Color(51, 153, 255));
		jLabel2.setText("uuid:");
		add(jLabel2);
		jLabel2.setBounds(90, 110, 70, 40);
		add(tfdUuid);
		tfdUuid.setBounds(170, 110, 200, 40);

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel3.setForeground(new java.awt.Color(204, 0, 102));
		jLabel3.setText("\u59d3\u540d:");
		add(jLabel3);
		jLabel3.setBounds(410, 110, 70, 40);
		add(tfdName);
		tfdName.setBounds(480, 110, 220, 40);

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel6.setForeground(new java.awt.Color(0, 204, 255));
		jLabel6.setText("\u7528\u6237\u7c7b\u578b\uff1a");
		add(jLabel6);
		jLabel6.setBounds(80, 260, 140, 40);
		add(strType);
		strType.setBounds(220, 260, 280, 40);

		btnDelete.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		btnDelete.setText("\u5220\u9664");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});
		add(btnDelete);
		btnDelete.setBounds(100, 340, 160, 50);

		btnBack.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		btnBack.setForeground(new java.awt.Color(153, 0, 51));
		btnBack.setText("\u8fd4\u56de");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});
		add(btnBack);
		btnBack.setBounds(410, 340, 160, 50);

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel4.setForeground(new java.awt.Color(204, 204, 255));
		jLabel4.setText("\u5bc6\u7801\uff1a");
		add(jLabel4);
		jLabel4.setBounds(90, 190, 80, 30);
		add(ptfPwd);
		ptfPwd.setBounds(180, 190, 320, 40);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		UserEbi ebi=UserEboFactory.getUserEbi();
		UserModel user=ebi.getSingle(uuid);
		boolean isDelete=ebi.deleteUser(user);
		if(isDelete){
			back();
		}else{
			JOptionPane.showMessageDialog(null, "要删除的用户已不存在");
			return ;
		}
	}

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
		back();
	}

	private void back() {
		mainFrame.setContentPane(new UserListPanel(mainFrame));
		mainFrame.validate();

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnDelete;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField ptfPwd;
	private javax.swing.JTextField strType;
	private javax.swing.JTextField tfdName;
	private javax.swing.JTextField tfdUuid;
	// End of variables declaration//GEN-END:variables

}