/*
 * InListPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.in.ui;

import java.util.List;
import java.util.Map;

import javax.swing.JFrame;

import cn.hncu.bookStore.in.business.factory.InMainEbiFactory;
import cn.hncu.bookStore.in.vo.InDetailModel;
import cn.hncu.bookStore.in.vo.InMainModel;

/**
 *
 * @author  __USER__
 */
public class InListPanel extends javax.swing.JPanel {
	private JFrame mainFrame = null;
	private Map<InMainModel, List<InDetailModel>> map;

	/** Creates new form InListPanel */
	public InListPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
		map = InMainEbiFactory.getInMainEbi().getAll();
		myInitDate();
	}

	public InListPanel(JFrame mainFrame,
			Map<InMainModel, List<InDetailModel>> map) {
		this.mainFrame=mainFrame;
		
		initComponents();
		this.map=map;
		myInitDate();
	}

	private void myInitDate() {
		jListInMain.setListData(map.keySet().toArray());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		btnAdd = new javax.swing.JButton();
		btnQuery = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListInMain = new javax.swing.JList();
		jScrollPane2 = new javax.swing.JScrollPane();
		jListInDetail = new javax.swing.JList();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel1.setForeground(new java.awt.Color(255, 102, 51));
		jLabel1.setText("\u8fdb\u8d27\u754c\u9762");
		add(jLabel1);
		jLabel1.setBounds(260, 40, 170, 40);

		btnAdd.setText("\u6dfb\u52a0");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});
		add(btnAdd);
		btnAdd.setBounds(90, 420, 130, 40);

		btnQuery.setText("\u67e5\u8be2");
		btnQuery.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQueryActionPerformed(evt);
			}
		});
		add(btnQuery);
		btnQuery.setBounds(510, 420, 130, 40);

		jListInMain.setFont(new java.awt.Font("ËÎÌו", 1, 18));
		jListInMain.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jListInMain
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt) {
						jListInMainValueChanged(evt);
					}
				});
		jScrollPane1.setViewportView(jListInMain);

		add(jScrollPane1);
		jScrollPane1.setBounds(0, 110, 340, 210);

		jListInDetail.setFont(new java.awt.Font("ËÎÌו", 1, 18));
		jListInDetail.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(jListInDetail);

		add(jScrollPane2);
		jScrollPane2.setBounds(350, 100, 360, 270);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {
		mainFrame.setContentPane(new InQueryPanel(mainFrame));
		mainFrame.validate();
	}

	private void jListInMainValueChanged(
			javax.swing.event.ListSelectionEvent evt) {
		InMainModel inMain = (InMainModel) jListInMain.getSelectedValue();
		List<InDetailModel> inDetails = map.get(inMain);

		jListInDetail.setListData(inDetails.toArray());
	}

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
		mainFrame.setContentPane(new InAddPanel(mainFrame));
		mainFrame.validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnQuery;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList jListInDetail;
	private javax.swing.JList jListInMain;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	// End of variables declaration//GEN-END:variables

}