/*
 * BookAddPanle.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.book.ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.book.business.factory.BookEbiFactory;
import cn.hncu.bookStore.book.vo.BookModel;
import cn.hncu.bookStore.book.vo.BookQueryModel;

/**
 *
 * @author  __USER__
 */
public class BookAddPanle extends javax.swing.JPanel {
	private JFrame mainFrame = null;

	/** Creates new form BookAddPanle */
	public BookAddPanle(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tfdName = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tfdInPrice = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		tfdSalePrice = new javax.swing.JTextField();
		btnBack = new javax.swing.JButton();
		btnAdd = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel1.setForeground(new java.awt.Color(0, 51, 255));
		jLabel1.setText("\u56fe\u4e66\u6dfb\u52a0\u754c\u9762");
		add(jLabel1);
		jLabel1.setBounds(250, 30, 230, 60);

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel3.setForeground(new java.awt.Color(204, 0, 102));
		jLabel3.setText("\u56fe\u4e66\u540d\u79f0:");
		add(jLabel3);
		jLabel3.setBounds(50, 130, 110, 40);
		add(tfdName);
		tfdName.setBounds(190, 130, 220, 40);

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel4.setText("\u56fe\u4e66\u8fdb\u4ef7:");
		add(jLabel4);
		jLabel4.setBounds(70, 210, 80, 50);
		add(tfdInPrice);
		tfdInPrice.setBounds(190, 210, 270, 40);

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel5.setText("\u56fe\u4e66\u552e\u4ef7:");
		add(jLabel5);
		jLabel5.setBounds(70, 290, 80, 50);
		add(tfdSalePrice);
		tfdSalePrice.setBounds(190, 290, 270, 40);

		btnBack.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		btnBack.setText("\u8fd4\u56de");
		add(btnBack);
		btnBack.setBounds(400, 400, 130, 50);

		btnAdd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		btnAdd.setText("\u6dfb\u52a0");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});
		add(btnAdd);
		btnAdd.setBounds(120, 400, 130, 50);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
		//1收集参数
		
		String name = tfdName.getText();
		double inPrice = Double.valueOf(tfdInPrice.getText());
		double salePrice = Double.valueOf(tfdSalePrice.getText());
		//2
		BookModel book = new BookModel();
		
		book.setName(name);
		book.setInPrice(inPrice);
		book.setSalePrice(salePrice);
		//3
		boolean isAdd = BookEbiFactory.getBookEbi().addBook(book);
		if (isAdd) {
			mainFrame.setContentPane(new BookListPanle(mainFrame));
			mainFrame.validate();
		} else {
			JOptionPane.showMessageDialog(null, "图书已存在");
			return;
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnBack;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField tfdInPrice;
	private javax.swing.JTextField tfdName;
	private javax.swing.JTextField tfdSalePrice;
	// End of variables declaration//GEN-END:variables

}