/*
 * BookStore.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore;

import sun.util.logging.resources.logging;
import cn.hncu.bookStore.book.ui.BookListPanle;
import cn.hncu.bookStore.common.login.ui.LoginPanel;
import cn.hncu.bookStore.in.ui.InListPanel;
import cn.hncu.bookStore.out.ui.OutListPanel;
import cn.hncu.bookStore.store.ui.StockListPanel;
import cn.hncu.bookStore.user.ui.UserListPanel;

/**
 * 
 * @author <a href="mailto:wyj950411@foxmail.com">¾ü½Ö</a>
 *
 * @version 1.0 2016-4-7
 */
public class BookStore extends javax.swing.JFrame {

	/** Creates new form BookStore */
	public BookStore() {
		initComponents();
		this.setContentPane(new LoginPanel(this));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		openMenuItem = new javax.swing.JMenuItem();
		saveMenuItem = new javax.swing.JMenuItem();
		saveAsMenuItem = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		cutMenuItem = new javax.swing.JMenuItem();
		copyMenuItem = new javax.swing.JMenuItem();
		pasteMenuItem = new javax.swing.JMenuItem();
		deleteMenuItem = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenuItemUser = new javax.swing.JMenuItem();
		jMenuItemBook = new javax.swing.JMenuItem();
		jMenuItemIn = new javax.swing.JMenuItem();
		jMenuItemOut = new javax.swing.JMenuItem();
		jMenuItemStock = new javax.swing.JMenuItem();
		jMenuItem1 = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		contentsMenuItem = new javax.swing.JMenuItem();
		aboutMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(800, 600));

		fileMenu.setText("File");

		openMenuItem.setText("Open");
		fileMenu.add(openMenuItem);

		saveMenuItem.setText("Save");
		fileMenu.add(saveMenuItem);

		saveAsMenuItem.setText("Save As ...");
		fileMenu.add(saveAsMenuItem);

		exitMenuItem.setText("Exit");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		editMenu.setText("Edit");

		cutMenuItem.setText("Cut");
		editMenu.add(cutMenuItem);

		copyMenuItem.setText("Copy");
		editMenu.add(copyMenuItem);

		pasteMenuItem.setText("Paste");
		editMenu.add(pasteMenuItem);

		deleteMenuItem.setText("Delete");
		editMenu.add(deleteMenuItem);

		menuBar.add(editMenu);

		jMenu1.setBackground(new java.awt.Color(102, 102, 255));
		jMenu1.setForeground(new java.awt.Color(255, 153, 153));
		jMenu1.setText("\u6a21\u5757");
		jMenu1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));

		jMenuItemUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_U,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemUser.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jMenuItemUser.setText("\u7528\u6237");
		jMenuItemUser.setEnabled(false);
		jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemUserActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemUser);

		jMenuItemBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_B,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemBook.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jMenuItemBook.setForeground(new java.awt.Color(102, 102, 255));
		jMenuItemBook.setText("\u56fe\u4e66");
		jMenuItemBook.setEnabled(false);
		jMenuItemBook.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemBookActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemBook);

		jMenuItemIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_I,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemIn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jMenuItemIn.setForeground(new java.awt.Color(51, 204, 0));
		jMenuItemIn.setText("\u8fdb\u8d27");
		jMenuItemIn.setEnabled(false);
		jMenuItemIn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemInActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemIn);

		jMenuItemOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_O,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemOut.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jMenuItemOut.setForeground(new java.awt.Color(255, 204, 204));
		jMenuItemOut.setText("\u9500\u552e");
		jMenuItemOut.setEnabled(false);
		jMenuItemOut.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemOutActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemOut);

		jMenuItemStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemStock.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jMenuItemStock.setForeground(new java.awt.Color(255, 51, 51));
		jMenuItemStock.setText("\u5e93\u5b58");
		jMenuItemStock.setEnabled(false);
		jMenuItemStock.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemStockActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemStock);

		jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_X,
				java.awt.event.InputEvent.ALT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jMenuItem1.setText("\u6ce8\u9500");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		menuBar.add(jMenu1);

		helpMenu.setText("Help");

		contentsMenuItem.setText("Contents");
		helpMenu.add(contentsMenuItem);

		aboutMenuItem.setText("About");
		helpMenu.add(aboutMenuItem);

		menuBar.add(helpMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 279,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.setContentPane(new LoginPanel(this));
		this.validate();
		this.getjMenuItemUser().setEnabled(false);
		this.getjMenuItemBook().setEnabled(false);
		this.getjMenuItemIn().setEnabled(false);
		this.getjMenuItemOut().setEnabled(false);
		this.getjMenuItemStock().setEnabled(false);
	}

	private void jMenuItemStockActionPerformed(java.awt.event.ActionEvent evt) {
		this.setContentPane(new StockListPanel(this));
		this.validate();
	}

	private void jMenuItemOutActionPerformed(java.awt.event.ActionEvent evt) {
		this.setContentPane(new OutListPanel(this));
		this.validate();
	}

	public javax.swing.JMenuItem getjMenuItemBook() {
		return jMenuItemBook;
	}

	public javax.swing.JMenuItem getjMenuItemIn() {
		return jMenuItemIn;
	}

	public javax.swing.JMenuItem getjMenuItemOut() {
		return jMenuItemOut;
	}

	public javax.swing.JMenuItem getjMenuItemStock() {
		return jMenuItemStock;
	}

	public javax.swing.JMenuItem getjMenuItemUser() {
		return jMenuItemUser;
	}

	private void jMenuItemInActionPerformed(java.awt.event.ActionEvent evt) {
		this.setContentPane(new InListPanel(this));
		this.validate();
	}

	private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {
		this.setContentPane(new UserListPanel(this));
		this.validate();
	}

	private void jMenuItemBookActionPerformed(java.awt.event.ActionEvent evt) {
		this.setContentPane(new BookListPanle(this));
		this.validate();
	}

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}//GEN-LAST:event_exitMenuItemActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BookStore().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentsMenuItem;
	private javax.swing.JMenuItem copyMenuItem;
	private javax.swing.JMenuItem cutMenuItem;
	private javax.swing.JMenuItem deleteMenuItem;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItemBook;
	private javax.swing.JMenuItem jMenuItemIn;
	private javax.swing.JMenuItem jMenuItemOut;
	private javax.swing.JMenuItem jMenuItemStock;
	private javax.swing.JMenuItem jMenuItemUser;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openMenuItem;
	private javax.swing.JMenuItem pasteMenuItem;
	private javax.swing.JMenuItem saveAsMenuItem;
	private javax.swing.JMenuItem saveMenuItem;
	// End of variables declaration//GEN-END:variables

}