/*
 * LoginPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.common.login.ui;

import java.util.List;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.BookStore;
import cn.hncu.bookStore.common.UserTypeEnum;
import cn.hncu.bookStore.common.login.business.factory.LoginEbiFactory;
import cn.hncu.bookStore.user.business.factory.UserEboFactory;
import cn.hncu.bookStore.user.vo.UserModel;
import cn.hncu.bookStore.utils.SetBack;

/**
 *
 * @author  __USER__
 */
public class LoginPanel extends javax.swing.JPanel {
	private BookStore app = null;

	/** Creates new form LoginPanel */
	public LoginPanel(BookStore app) {
		this.app = app;
		initComponents();
		SetBack.setBack(this,"delete");
	}

	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tfdName = new javax.swing.JTextField();
		tfdPwd = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("宋体", 1, 48));
		jLabel1.setForeground(new java.awt.Color(255, 51, 51));
		jLabel1.setText("\u767b\u5f55\u754c\u9762");
		add(jLabel1);
		jLabel1.setBounds(230, 20, 210, 50);

		jLabel2.setFont(new java.awt.Font("宋体", 1, 18));
		jLabel2.setForeground(new java.awt.Color(51, 255, 102));
		jLabel2.setText("\u5bc6\u7801\uff1a");
		add(jLabel2);
		jLabel2.setBounds(140, 210, 90, 40);

		jLabel3.setFont(new java.awt.Font("宋体", 1, 18));
		jLabel3.setForeground(new java.awt.Color(51, 255, 102));
		jLabel3.setText("\u7528\u6237\u540d\uff1a");
		add(jLabel3);
		jLabel3.setBounds(140, 130, 90, 40);

		tfdName.setFont(new java.awt.Font("宋体", 1, 18));
		add(tfdName);
		tfdName.setBounds(220, 130, 280, 50);

		tfdPwd.setFont(new java.awt.Font("宋体", 1, 18));
		add(tfdPwd);
		tfdPwd.setBounds(220, 210, 280, 50);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jButton1.setForeground(new java.awt.Color(255, 0, 0));
		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		add(jButton1);
		jButton1.setBounds(250, 330, 180, 50);
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//1
		String userName = tfdName.getText();
		String pwd = new String(tfdPwd.getPassword());

		//2
		String results = LoginEbiFactory.getLoginEbi().login(userName, pwd);

		//3
		if (results != null) {
			JOptionPane.showMessageDialog(app, results);
			return;
		}
		//4
		app.setContentPane(new WelcomePanel(app));
		app.validate();

		//点亮模块
		UserModel user = null;
		List<UserModel> users = UserEboFactory.getUserEbi().getAll();
		for (UserModel model : users) {
			if (model.getName().equals(userName)) {
				user = model;
			}
		}
		//超级管理员
		if (user.getType() == UserTypeEnum.ADMIN.getType()) {
			app.getjMenuItemUser().setEnabled(true);
			app.getjMenuItemBook().setEnabled(true);
			app.getjMenuItemIn().setEnabled(true);
			app.getjMenuItemOut().setEnabled(true);
			app.getjMenuItemStock().setEnabled(true);
		}
		//图书管理员
		if (user.getType() == UserTypeEnum.BOOK.getType()) {
			app.getjMenuItemBook().setEnabled(true);
		}
		//进货管理员
		if (user.getType() == UserTypeEnum.IN.getType()) {
			app.getjMenuItemIn().setEnabled(true);
		}
		//销售管理员
		if (user.getType() == UserTypeEnum.OUT.getType()) {
			app.getjMenuItemOut().setEnabled(true);
		}
		//库存管理员
		if (user.getType() == UserTypeEnum.STOCK.getType()) {
			app.getjMenuItemStock().setEnabled(true);
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField tfdName;
	private javax.swing.JPasswordField tfdPwd;
	// End of variables declaration//GEN-END:variables

}