/*
 * WelcomePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.common.login.ui;

import cn.hncu.bookStore.BookStore;
import cn.hncu.bookStore.utils.SetBack;

/**
 *
 * @author  __USER__
 */
public class WelcomePanel extends javax.swing.JPanel {
	private BookStore app = null;

	/** Creates new form WelcomePanel */
	public WelcomePanel(BookStore app) {
		this.app = app;
		initComponents();
		SetBack.setBack(this,"delete");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel3.setFont(new java.awt.Font("ËÎÌו", 1, 42));
		jLabel3.setForeground(new java.awt.Color(204, 204, 255));
		jLabel3.setText("\u6b22\u8fce\u8fdb\u5165\u519b\u8857\u7684\u56fe\u4e66\u7ba1\u7406\u7cfb\u7edf\uff01\uff01\uff01");
		add(jLabel3);
		jLabel3.setBounds(20, 150, 740, 160);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables

}