/*
 * StockQueryPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.store.ui;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.book.business.factory.BookEbiFactory;
import cn.hncu.bookStore.book.vo.BookModel;
import cn.hncu.bookStore.store.business.factory.StockEbiFactory;
import cn.hncu.bookStore.store.dao.factory.StockDAOFactory;
import cn.hncu.bookStore.store.vo.StockModel;
import cn.hncu.bookStore.store.vo.StockQueryModel;

/**
 *
 * @author  __USER__
 */
public class StockQueryPanel extends javax.swing.JPanel {
	private JFrame mainFrame = null;

	/** Creates new form StockQueryPanel */
	public StockQueryPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
		myInitDate();

	}

	private void myInitDate() {
		List<BookModel> books = BookEbiFactory.getBookEbi().getAll();
		for (BookModel book : books) {
			combBook.addItem(book.getName());
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tfdUuid = new javax.swing.JTextField();
		tfdSumNum2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tfdSumNum = new javax.swing.JTextField();
		combBook = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		btnBack = new javax.swing.JButton();
		btnQuery = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel1.setForeground(new java.awt.Color(255, 51, 51));
		jLabel1.setText("\u5e93\u5b58\u67e5\u8be2\u754c\u9762");
		add(jLabel1);
		jLabel1.setBounds(240, 20, 250, 60);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel2.setText("\u5e93\u5b58\u6700\u5c0f\u6570\u91cf\uff1a");
		add(jLabel2);
		jLabel2.setBounds(40, 220, 140, 40);

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel3.setText("\u56fe\u4e66\u540d\uff1a");
		add(jLabel3);
		jLabel3.setBounds(400, 130, 100, 40);

		tfdUuid.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		add(tfdUuid);
		tfdUuid.setBounds(180, 130, 160, 40);

		tfdSumNum2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		add(tfdSumNum2);
		tfdSumNum2.setBounds(490, 220, 160, 40);

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel4.setText("\u5e93\u5b58\u6700\u5c0f\u6570\u91cf\uff1a");
		add(jLabel4);
		jLabel4.setBounds(350, 220, 150, 40);

		tfdSumNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		add(tfdSumNum);
		tfdSumNum.setBounds(180, 220, 160, 40);

		combBook.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		combBook.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "选择所有" }));
		add(combBook);
		combBook.setBounds(490, 130, 160, 40);

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel5.setText("\u5e93\u5b58\u7f16\u53f7\uff1a");
		add(jLabel5);
		jLabel5.setBounds(70, 130, 100, 40);

		btnBack.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		btnBack.setText("\u8fd4\u56de");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});
		add(btnBack);
		btnBack.setBounds(430, 350, 140, 50);

		btnQuery.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		btnQuery.setText("\u67e5\u8be2");
		btnQuery.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQueryActionPerformed(evt);
			}
		});
		add(btnQuery);
		btnQuery.setBounds(130, 350, 140, 50);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
		mainFrame.setContentPane(new StockListPanel(mainFrame));
		mainFrame.validate();
	}

	//GEN-END:initComponents

	private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {
		//1
		String uuid = tfdUuid.getText();
		
		String bookUuid = null;
		if (combBook.getSelectedIndex() > 0) {
			bookUuid = BookEbiFactory.getBookEbi().getBookByName(combBook.getSelectedItem().toString()).getUuid();
		}

		int sumNum = 0;
		String strNum = tfdSumNum.getText();
		if(strNum!=null && strNum.trim().length()>0){
			try {
				sumNum = Integer.parseInt(strNum);
				if (sumNum < 0) {
					throw new NumberFormatException();
				}
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(null, "图书最小数量格式输入错误");
				return;
			}
		}
		int sumNum2 = 0;
		String strNum2 = tfdSumNum2.getText();
		if(strNum2!=null && strNum2.trim().length()>0){
			try {
				sumNum2 = Integer.parseInt(strNum2);
				if (sumNum < 0) {
					throw new NumberFormatException();
				}
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(null, "图书最大数量格式输入错误");
				return;
			}
		}

		//2
		StockQueryModel sqm = new StockQueryModel();
		sqm.setUuid(uuid);
		sqm.setBookUuid(bookUuid);
		sqm.setSumNum(sumNum);
		sqm.setSumNum2(sumNum2);
		//3
		List<StockModel> results = StockEbiFactory.getStockEbi()
				.getByCondition(sqm);
		
		
		//4
		mainFrame.setContentPane(new StockListPanel(mainFrame, results));
		mainFrame.validate();

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnQuery;
	private javax.swing.JComboBox combBook;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField tfdSumNum;
	private javax.swing.JTextField tfdSumNum2;
	private javax.swing.JTextField tfdUuid;
	// End of variables declaration//GEN-END:variables

}