/*
 * StockListPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.store.ui;

import java.util.List;

import javax.swing.JFrame;

import cn.hncu.bookStore.store.business.factory.StockEbiFactory;
import cn.hncu.bookStore.store.vo.StockModel;

/**
 *
 * @author  __USER__
 */
public class StockListPanel extends javax.swing.JPanel {
	private JFrame mainFrame = null;

	/** Creates new form StockListPanel */
	public StockListPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
		myInitDate();
	}

	public StockListPanel(JFrame mainFrame, List<StockModel> results) {
		this.mainFrame = mainFrame;
		initComponents();
		jListStock.setListData(results.toArray());
	}

	private void myInitDate() {
		List<StockModel> list = StockEbiFactory.getStockEbi().getAll();
		jListStock.setListData(list.toArray());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListStock = new javax.swing.JList();
		btnToQuery = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel1.setForeground(new java.awt.Color(255, 102, 102));
		jLabel1.setText("\u5e93\u5b58\u754c\u9762");
		add(jLabel1);
		jLabel1.setBounds(250, 30, 180, 60);

		jListStock.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jListStock.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jListStock);

		add(jScrollPane1);
		jScrollPane1.setBounds(90, 120, 570, 230);

		btnToQuery.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		btnToQuery.setForeground(new java.awt.Color(255, 102, 102));
		btnToQuery.setText("\u67e5\u8be2");
		btnToQuery.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnToQueryActionPerformed(evt);
			}
		});
		add(btnToQuery);
		btnToQuery.setBounds(240, 380, 190, 60);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnToQueryActionPerformed(java.awt.event.ActionEvent evt) {
		mainFrame.setContentPane(new StockQueryPanel(mainFrame));
		mainFrame.validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnToQuery;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList jListStock;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}